language: node_js
node_js:
  - "4.4.7"
install:
  - sudo apt-get install npm
  - npm config set registry http://registry.npmjs.org/
  - npm install
  # install codecov.io
  - npm install codecov.io
script:
  - npm test
after_success:
 # upload coverage data to codecov.io
 - cat coverage/*/lcov.info | codecov
