name: Build & Publish Maven Package

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      source_ref:
        description: "Branch, release tag, or commit hash to build"
        type: string
        required: true
      update_backend:
        description: "Update backend pom.xml with the above tag"
        type: boolean
        required: false
        default: 'false'

env:
  JAVA_VERSION: '21'
  JAVA_DIST: 'temurin'
  MAVEN_SERVER: 'ossrh'

jobs:
  github-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.source_ref }}

      - name: Checkout repository (automatic trigger)
        if: github.event_name == 'release'
        uses: actions/checkout@v4

      - name: Setup java for GitHub Packages
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DIST }}

      - name: Set maven version from source ref (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        run: mvn versions:set -DnewVersion=${{ inputs.source_ref }} -DgenerateBackupPoms=false

      - name: Set maven version from release tag (automatic trigger)
        if: github.event_name == 'release'
        run: mvn versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false

      - name: Publish package to GitHub Packages
        run: mvn -P github --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  maven-central:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.source_ref }}

      - name: Checkout repository (automatic trigger)
        if: github.event_name == 'release'
        uses: actions/checkout@v4

      - name: Setup java for Maven Central
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DIST }}
          server-id: ${{ env.MAVEN_SERVER }}
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_CENTRAL_GPG_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Test settings file
        run: |
          cat /home/runner/.m2/settings.xml
      - name: Set maven version from source ref (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        run: mvn versions:set -DnewVersion=${{ inputs.source_ref }} -DgenerateBackupPoms=false

      - name: Set maven version from release tag (automatic trigger)
        if: github.event_name == 'release'
        run: mvn versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false

      - name: Publish package to Maven Central
        run: mvn --settings /home/runner/.m2/settings.xml -P maven-central --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_CENTRAL_GPG_PASSPHRASE }}

  update-backend:
    runs-on: ubuntu-latest
    needs: [github-packages, maven-central]
    if: inputs.update_backend == 'true'
    steps:
      - name: Set up SSH
        if: github.event_name == 'release'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.BACKEND_REPO_TOKEN }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Set up git
        if: github.event_name == 'release'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Checkout cbioportal/cbioportal
        if: github.event_name == 'release'
        run: |
          git clone git@github.com:cBioPortal/cbioportal.git

      - name: Update backend pom with new frontend version
        if: github.event_name == 'release'
        run: |
          TAG=${{ github.event.release.tag_name }}
          cd cbioportal
          sed -i "s|<version>\(.*\)-SNAPSHOT</version>|<version>$TAG</version>|" pom.xml
          sed -i "s|<frontend.version>.*</frontend.version>|<frontend.version>$TAG</frontend.version>|" pom.xml
          git add pom.xml
          git commit -m "Frontend $TAG"
          git push
