name: Build & Publish NPM to GitHub Packages

on:
  push:
  workflow_dispatch:

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '15.2.1'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@cbioportal'
      
      - name: Install yarn
        run: npm install -g yarn@1.22.5

      - name: Verify yarn
        run: yarn --version

      - run: yarn
      - run: yarn publish --access public --new-version 'v6.0.28'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}